# Generated by Django 4.1 on 2024-05-30 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0002_alter_rate_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='calculator_app.city', verbose_name='Город отправитель'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='calculator_app.city', verbose_name='Город получатель'),
        ),
    ]
