# Generated by Django 4.1 on 2024-06-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0003_alter_rate_city_from_alter_rate_city_to'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rate',
            managers=[
            ],
        ),
    ]
