# Generated by Django 4.1 on 2024-07-24 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_app', '0004_alter_rate_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('cost_by_weight_0_25', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<25')),
                ('cost_by_weight_25_50', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<50')),
                ('cost_by_weight_50_150', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='51-150')),
                ('cost_by_weight_150_300', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='151-300')),
                ('cost_by_weight_300_500', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='301-500')),
                ('cost_by_weight_500_1000', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='501-1000')),
                ('cost_by_weight_1000_1500', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='1001-1500')),
                ('cost_by_weight_1500_2000', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='1501-2000')),
                ('cost_by_weight_2000_3000', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='2001-3000')),
                ('cost_by_weight_3000_5000', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='3001-5000')),
                ('cost_by_weight_5000_10000', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='5001-10000')),
                ('cost_by_weight_10000_inf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='>10000')),
                ('cost_by_volume_0_01', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<0.1')),
                ('cost_by_volume_01_02', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<0.2')),
                ('cost_by_volume_02_06', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='0.2-0.6')),
                ('cost_by_volume_06_12', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='0.6-1.2')),
                ('cost_by_volume_12_20', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='1.2-2.0')),
                ('cost_by_volume_20_40', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='2.0-4.0')),
                ('cost_by_volume_40_60', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='4.0-6.0')),
                ('cost_by_volume_60_80', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='6.0-8.0')),
                ('cost_by_volume_80_120', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='8.0-12.0')),
                ('cost_by_volume_120_200', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='12.0-20.0')),
                ('cost_by_volume_200_400', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='20.0-40.0')),
                ('cost_by_volume_400_inf', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='>40.0')),
                ('city_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedition_rates_to', to='calculator_app.city', verbose_name='Город получатель')),
            ],
            options={
                'verbose_name': 'Тариф на експедирование',
                'verbose_name_plural': 'Тарифы на экспедирование',
                'ordering': ['city_to'],
            },
        ),
        migrations.DeleteModel(
            name='LastMileRate',
        ),
    ]
