# Generated by Django 4.1 on 2024-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Dg1QrkzhLB6FIUl74EDTkk$+U8ccTcyS3PXthEqq0xQFa5iDglt3SPZr+Xf1vtS29w=', max_length=128, verbose_name='password'),
        ),
    ]
