# Generated by Django 4.1 on 2024-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$8DDTVx1x89dqvF8RyJTFg6$2mVfUWBR9wCgsa4kzk56qibyBR5VTK+KLVfDikSC1To=', max_length=128, verbose_name='password'),
        ),
    ]
