# Generated by Django 4.1 on 2024-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$TF6y2NPsdY4wvfzP0iI09T$EA1v76PhZtpc4JCVv2G3QtNDuCI+IocDKIBkgXL3XvQ=', max_length=128, verbose_name='password'),
        ),
    ]
