# Generated by Django 4.1 on 2024-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$San51OyS40oxrrbkzcY5ho$2vFAgzURugrsvHhdcbhsV/EyFpqqMimVh3I3R5z2LdI=', max_length=128, verbose_name='password'),
        ),
    ]
