# Generated by Django 4.1 on 2024-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$WRh0l5oNEscF9dX7bK43kR$PRZy9xbKrO0Wxd6tvHCMq1KrrdegEsPSaSlM64LK3jA=', max_length=128, verbose_name='password'),
        ),
    ]
