# Generated by Django 4.1 on 2024-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$qnRBHbmHxpCmzMMI5BoNeW$2GgzFjld+6yM43AVJGuV3b1l2J1TQjQTkUdx5CE2eos=', max_length=128, verbose_name='password'),
        ),
    ]
