# Generated by Django 4.1 on 2024-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$0IjdGN7Ygrhra9Up6AlH4k$4IrYq8h9u1Hzh8nLCFO7kKUTZosJYYrw5JACbxhAJXI=', max_length=128, verbose_name='password'),
        ),
    ]
