# Generated by Django 4.1 on 2024-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$CcxbIbh5qzFpeuYfUh6oQf$vTzp4UfBOnVXk1RccE5AUueeVmKMvX6DCYTKFfSEnhk=', max_length=128, verbose_name='password'),
        ),
    ]
