# Generated by Django 4.1 on 2024-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$GU6yfVIHjmM4J02gIzc3jM$hi9sDjXtWkb3chQIAq0rDnTW9IAayJmpn5kM7LkIB+o=', max_length=128, verbose_name='password'),
        ),
    ]
