# Generated by Django 4.1 on 2024-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$o0KqItxaGae3BofwtgyeVZ$x5Wf4yRuXGJjiMhyFIATvUP593Mh2MisqrZDNzuwfBk=', max_length=128, verbose_name='password'),
        ),
    ]
