# Generated by Django 4.1 on 2024-05-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$RH8v1N1H5jmBuIXQhOmeAS$vii7yAflQeJDumrRDUHvxyfmnJQFSdKTgD7NnViItFU=', max_length=128, verbose_name='password'),
        ),
    ]
