# Generated by Django 4.1 on 2024-05-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities_from', to='order_app.city', verbose_name='Город отправитель'),
        ),
        migrations.AddField(
            model_name='rate',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities_to', to='order_app.city', verbose_name='Город получатель'),
        ),
    ]
