# Generated by Django 4.1 on 2024-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_remove_rate_name_rate_city_from_rate_city_to'),
    ]

    operations = [
    ]
