# Generated by Django 4.1 on 2024-05-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_remove_rate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_01_02',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<0.2'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_02_06',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='0.2-0.6'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_06_12',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='0.6-1.2'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_0_01',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<0.1'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_12_20',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='12.0-20.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_20_40',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='20.0-40.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_40_60',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='4.0-6.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_40_inf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='>40.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_60_80',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='6.0-8.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_80_120',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='8.0-12.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_10000_inf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='>10000'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_1000_1500',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='1001-1500'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_1500_2000',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='1501-2000'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_150_300',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='151-300'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_2000_3000',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='2001-3000'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_25_50',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<50'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_3000_5000',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='3001-5000'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_300_500',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='301-500'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_5000_10000',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='5001-10000'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_500_1000',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='501-1000'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_weight_50_150',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='51-150'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='cost_by_weight_0_25',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='<25'),
        ),
    ]
