# Generated by Django 4.1 on 2024-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_rate_cost_by_volume_01_02_rate_cost_by_volume_02_06_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='cost_by_volume_40_inf',
            new_name='cost_by_volume_400_inf',
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_120_200',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='12.0-20.0'),
        ),
        migrations.AddField(
            model_name='rate',
            name='cost_by_volume_200_400',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='20.0-40.0'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='cost_by_volume_12_20',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='1.2-2.0'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='cost_by_volume_20_40',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='2.0-4.0'),
        ),
    ]
