# Generated by Django 4.1 on 2024-05-18 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator_app', '0001_initial'),
        ('order_app', '0008_remove_lastmilerate_rate_item_remove_rate_city_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Вес, см')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Длина, см')),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Ширина, см')),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Высота, см')),
                ('volume', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3')),
                ('seats', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, verbose_name='Количество мест, шт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('number', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Номер')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата')),
                ('from_address', models.BooleanField(default=False, verbose_name='Забрать по адресу')),
                ('address_from', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес забора')),
                ('date_from', models.DateField(verbose_name='Дата забора')),
                ('time_from', models.CharField(choices=[('t1', '09:00-19:00'), ('t2', '19:00-23:00'), ('t3', '23:00-08:00')], default='t1', max_length=2, verbose_name='Время забора')),
                ('to_address', models.BooleanField(default=False, verbose_name='Доставить по адресу')),
                ('address_to', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес доставки')),
                ('date_to', models.DateField(verbose_name='Дата доставки')),
                ('time_to', models.CharField(choices=[('t1', '09:00-19:00'), ('t2', '19:00-23:00'), ('t3', '23:00-08:00')], default='t1', max_length=2, verbose_name='Время доставки')),
                ('insurance', models.BooleanField(default=False, verbose_name='Страхование груза')),
                ('return_docs', models.BooleanField(default=False, verbose_name='Возврат пакета документов')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Объявленная стоимость')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_from', to='calculator_app.city', verbose_name='Откуда')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_to', to='calculator_app.city', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('soft_packaging', models.BooleanField(default=False, verbose_name='Мягкая упаковка')),
                ('Crate', models.BooleanField(default=False, verbose_name='Обрешетка')),
                ('palletizing', models.BooleanField(default=False, verbose_name='Паллетирование')),
                ('pallet_board', models.BooleanField(default=False, verbose_name='Паллетный борт')),
                ('seal_bag', models.BooleanField(default=False, verbose_name='Мешок-пломба')),
                ('cardboard_box', models.BooleanField(default=False, verbose_name='Картонная коробка')),
                ('high_security_cargo', models.BooleanField(default=False, verbose_name='Режимный груз')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_app.cargo', verbose_name='Груз')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order', verbose_name='Заказ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
