# Generated by Django 4.1 on 2024-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Груз', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Описание груза'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Вес, кг'),
        ),
    ]
