# Generated by Django 4.1 on 2024-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_alter_cargo_options_alter_cargo_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'ordering': ['order'], 'verbose_name': 'Строка заказа', 'verbose_name_plural': 'Строки заказов'},
        ),
        migrations.AddField(
            model_name='order',
            name='declared_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Объявленная стоимость'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Описание груза'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='seats',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15, verbose_name='Количество мест, шт'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='volume',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость'),
        ),
    ]
