# Generated by Django 4.1 on 2024-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0013_order_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_from',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='email_payer',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='email_to',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='face_from',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='order',
            name='face_payer',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='order',
            name='face_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='order',
            name='form_from',
            field=models.CharField(choices=[('FZ', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('OR', 'Физическое лицо')], default='FZ', max_length=2, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='order',
            name='form_payer',
            field=models.CharField(choices=[('FZ', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('OR', 'Физическое лицо')], default='FZ', max_length=2, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='order',
            name='form_to',
            field=models.CharField(choices=[('FZ', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('OR', 'Физическое лицо')], default='FZ', max_length=2, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_from',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_payer',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer',
            field=models.CharField(choices=[('SD', 'Отправитель'), ('RP', 'Получатель'), ('PR', 'Третье лицо')], default='SD', max_length=2, verbose_name='Плательщик'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_from',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_payer',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_to',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон'),
        ),
    ]
