# Generated by Django 4.1 on 2024-05-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_order_email_from_order_email_payer_order_email_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='Crate',
            new_name='crate',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='seats',
            field=models.IntegerField(default=1, verbose_name='Количество мест, шт'),
        ),
    ]
