# Generated by Django 4.1 on 2024-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_rename_crate_itemorder_crate_alter_cargo_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Дата забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
