# Generated by Django 4.1 on 2024-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0017_alter_order_form_from_alter_order_form_payer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='cardboard_box',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='crate',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='high_security_cargo',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='pallet_board',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='palletizing',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='seal_bag',
        ),
        migrations.RemoveField(
            model_name='itemorder',
            name='soft_packaging',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='hard_packaging',
            field=models.BooleanField(default=False, verbose_name='Жесткая упаковка'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='prr_from',
            field=models.BooleanField(default=False, verbose_name='Жесткая упаковка'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='prr_to',
            field=models.BooleanField(default=False, verbose_name='Жесткая упаковка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Время забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
    ]
