# Generated by Django 4.1 on 2024-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0019_alter_itemorder_prr_from_alter_itemorder_prr_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='palletizing',
            field=models.BooleanField(default=False, verbose_name='Паллетирование'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='soft_packaging',
            field=models.BooleanField(default=False, verbose_name='Мягкая упаковка'),
        ),
    ]
