# Generated by Django 4.1 on 2024-06-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0020_itemorder_palletizing_itemorder_soft_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_time',
            field=models.BooleanField(default=False, verbose_name='Забрать по времени'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_time',
            field=models.BooleanField(default=False, verbose_name='Доставить ко времени'),
        ),
    ]
