# Generated by Django 4.1 on 2024-07-16 10:14

from django.db import migrations, models
import server.base


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0021_order_from_time_order_to_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uploaded',
            field=models.BooleanField(default=False, verbose_name='Выгружен в 1С'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=server.base.now, null=True, verbose_name='Дата'),
        ),
    ]
