# Generated by Django 4.1 on 2024-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$9jhDzZahqtteNys2rzWR6y$tXZ18HORfbN5wl7bAcf0FrFSUAEQsD30i3Fepbl1Ji4=', max_length=128, verbose_name='password'),
        ),
    ]
