# Generated by Django 4.1 on 2024-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Nz63y1cGyBEg9MqsnBM8Ze$eueKk+QPcPeqAeUvzTepXx6eDkXmpNFfx8tyvaGUbbM=', max_length=128, verbose_name='password'),
        ),
    ]
