# Generated by Django 4.1 on 2024-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$XqnlD123rZPEZx6DVnrAHl$X+eg9zb85E8FvgTxlsZNp4QM5f/TeUEr9pbAqmtD8oU=', max_length=128, verbose_name='password'),
        ),
    ]
