# Generated by Django 4.1 on 2024-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$dQCwV6IQEFiVEKONhBcpU6$WG+/p/o4ek1D2hmAxcDF6SvIdoDJmwEyoiDepMvL4xI=', max_length=128, verbose_name='password'),
        ),
    ]
