# Generated by Django 4.1 on 2024-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Bs3DBhXYM6bCIe2OQ2a7cq$Y+2F7XqA6XbUZiadi0poAyIbw3pmTY/Vc5mnwhh3RXg=', max_length=128, verbose_name='password'),
        ),
    ]
