# Generated by Django 4.1 on 2024-05-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$pBCoW8c1jjlIlxin2ce5Ug$fW7roWIMAoegkfUrV+d7Jev8vlWumqWqrj+MNkCH2dI=', max_length=128, verbose_name='password'),
        ),
    ]
