# Generated by Django 4.1 on 2024-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$PFTbeKzfwsz3C925WeNvoQ$av0I8OPooD085WvxdZL0yUbVUVscXM1eHzTq8Oj1QoE=', max_length=128, verbose_name='password'),
        ),
    ]
