# Generated by Django 4.1 on 2024-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$6SsLb21nYznQmi0SLFyrKF$j42Dkt/4Yh9CVTx6MGQ6Dh3AhCYuUH8a5seh5YVesAw=', max_length=128, verbose_name='password'),
        ),
    ]
