# Generated by Django 4.1 on 2024-05-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$BfiXFTjl3nMg4Mbueo8BVL$4m/zKxSwyN/e1wRZz52QwlWke03WcPojzDYy5iid73A=', max_length=128, verbose_name='password'),
        ),
    ]
