# Generated by Django 4.1 on 2024-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$vNyzWYOkvMwKnG0aOuuJMP$szrohwpSZMIFo9pLrkJyAQq3lwvkIqUEc13VmpDeuHc=', max_length=128, verbose_name='password'),
        ),
    ]
