# Generated by Django 4.1 on 2024-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$YHxzUpfCjl81JDpjzAwFOC$3pS23n4NFtgpwyV0uhUtwo/ZMTDLOwPP03z4XSoRvf8=', max_length=128, verbose_name='password'),
        ),
    ]
