# Generated by Django 4.1 on 2024-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$SX1wVISLTIMBr2fFyEfbN1$nPvnEQKmexgCnuP6OWUM1Vx+mW18ywqMgkL2WyTu6oo=', max_length=128, verbose_name='password'),
        ),
    ]
