# Generated by Django 4.1 on 2024-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$usJNmWPKyCNBch8GbYnJNm$r8iNWBKXg65DLqAcYZqY4SiqrdWE/UCR0uB8NAoIVQs=', max_length=128, verbose_name='password'),
        ),
    ]
