# Generated by Django 4.1 on 2024-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$OlFbMGurY3ZJGXb7W9zPy8$W6v55Bc49b4frc9RhWlRvvTaj5wajyEsaE1P9ex4E0U=', max_length=128, verbose_name='password'),
        ),
    ]
