# Generated by Django 4.1 on 2024-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$v1TR8PJL7SQLcEQFybpzlx$vAXuohLePPZl57hG8kAlS3EpAMsSCoEV2xoVTreBur8=', max_length=128, verbose_name='password'),
        ),
    ]
