# Generated by Django 4.1 on 2024-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$SRs2s1kmNMgihfG4AamRrf$4scuoJha8GGBLEe83pkEOFyrKR5JrPLft+5qs9fSyvE=', max_length=128, verbose_name='password'),
        ),
    ]
