# Generated by Django 4.1 on 2024-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$rtfkX9oczaUsng3LGnqOK6$Ys6qf9ak8ZoU0YpDLTA108G/iffxoq/k4297BtP2edk=', max_length=128, verbose_name='password'),
        ),
    ]
