# Generated by Django 4.1 on 2024-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$sI8e7E8xqhkAewsAmyVhiS$pBIgRTq+1wO/mi9n6KuX/fHbbgnlgeF9nPFn81eFVyI=', max_length=128, verbose_name='password'),
        ),
    ]
