# Generated by Django 4.1 on 2024-07-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0037_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$UkeXtbARuaeL183dKWDv0F$XDLBdpV59OrhPMJXrunX0xqhz/QQvXvac6MrJTwAA2Q=', max_length=128, verbose_name='password'),
        ),
    ]
