# Generated by Django 4.1 on 2024-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$p8RLFwnQE64J4qndrgPZ6x$VAnmEIe1BeJ+hHdQbwmqAfy0/O++Nzt7uSEF3AI/Wac=', max_length=128, verbose_name='password'),
        ),
    ]
