# Generated by Django 4.1 on 2024-07-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0040_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$cNBcEuC3QYD9o18iQDuh7B$uz0njNZGpmVh/n6cS+Gv64FC71ciNH8X/2oC2tDvFKQ=', max_length=128, verbose_name='password'),
        ),
    ]
