# Generated by Django 4.1 on 2024-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0041_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$9bqVHslX0sstv0nNMhtjiB$+MzEzSo7GplMp8pGrB6ljUQkG3IhlF3KW/YQ14YsMdQ=', max_length=128, verbose_name='password'),
        ),
    ]
