# Generated by Django 4.1 on 2024-07-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0042_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$RpSiToBErdweyogXvTWCNT$H7UMIAmQqmoGme94RGSqyBvb14sjBXWuoeM2xOw0MHA=', max_length=128, verbose_name='password'),
        ),
    ]
