# Generated by Django 4.1 on 2024-11-02 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0044_customer_alter_user_password_user_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$RfOXyveE3UGvxVqw9ikyQA$Nnc6msRwFT7Ojz1z/iTDXp3g9vv0/9/NrAEvTZDuWiU=', max_length=128, verbose_name='password'),
        ),
    ]
