# Generated by Django 4.1 on 2025-09-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0045_alter_customer_id_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$gQGsPIfVL7enTjuN53uOGP$xZWI2CNcb0spCHbF/NKQQLWPjjElh6IigMcZRcEsZ5E=', max_length=128, verbose_name='password'),
        ),
    ]
