# Generated by Django 4.1 on 2026-01-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$aL0P3kOMnAl85RW3KUwfVa$lEsiLzE6KaPp1bhOkey/7Z3EvogxUndYDMc4e0q7+2Y=', max_length=128, verbose_name='password'),
        ),
    ]
