# Generated by Django 4.1 on 2026-01-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0047_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$ygeVSH4rhDpEAQcnAubEtX$LFypS6452Q82nUS/nIfTFUVcpw1POo8EZ1z8pV9lR6o=', max_length=128, verbose_name='password'),
        ),
    ]
