# Generated by Django 4.1 on 2024-05-22 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0004_tag_news_author_news_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Const',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Электронная почта')),
                ('tel', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Константы',
                'verbose_name_plural': 'Константы',
                'ordering': ['-created_at'],
            },
        ),
    ]
