# Generated by Django 4.1 on 2024-05-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0006_const_crate_cost_const_insurance_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='const',
            old_name='crate_cost',
            new_name='hard_packaging_cost',
        ),
    ]
