# Generated by Django 4.1 on 2024-05-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0005_const'),
    ]

    operations = [
        migrations.AddField(
            model_name='const',
            name='crate_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Жесткая упаковка(обрешётка), руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Страхование, %'),
        ),
        migrations.AddField(
            model_name='const',
            name='min_warehouse_process_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Минимальная стоимость складской обработки грузов, руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='nigth_deliver_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Тариф ночной доставки (21.00-09.00), руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='prr_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Услуга ПРР, руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='return_docs_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Возврат документов, руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='time_deliver_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Доставка ко времени, руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='warehouse_process_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Складская обработка грузов, руб/м3'),
        ),
    ]
