# Generated by Django 4.1 on 2024-05-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0007_rename_crate_cost_const_hard_packaging_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='const',
            name='hard_packaging_min_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Жесткая упаковка(обрешётка) минимальная стоимость, руб'),
        ),
    ]
