# Generated by Django 4.1 on 2024-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0008_const_hard_packaging_min_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='const',
            name='palletizing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость паллетирования, руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='palletizing_min_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Минимальная стоимость паллетирования, руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='soft_packaging_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Мягкая упаковка (пупырка), руб'),
        ),
        migrations.AddField(
            model_name='const',
            name='soft_packaging_min_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Мягкая упаковка (пупырка) минимальная стоимость, руб'),
        ),
        migrations.AlterField(
            model_name='const',
            name='hard_packaging_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Жесткая упаковка (обрешётка), руб'),
        ),
        migrations.AlterField(
            model_name='const',
            name='hard_packaging_min_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Жесткая упаковка (обрешётка) минимальная стоимость, руб'),
        ),
    ]
