# Generated by Django 4.1 on 2024-06-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0009_const_palletizing_cost_const_palletizing_min_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='const',
            name='palletizing_min_cost',
        ),
        migrations.RemoveField(
            model_name='const',
            name='soft_packaging_min_cost',
        ),
    ]
