# Generated by Django 4.1 on 2024-07-05 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0010_remove_const_palletizing_min_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Электронная почта')),
                ('tel', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['-created_at'],
            },
        ),
    ]
