# Generated by Django 4.1 on 2024-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0011_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='const',
            name='min_insurance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Минимальная сумма страхования'),
        ),
    ]
