# Generated by Django 4.1 on 2025-09-26 03:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0013_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=150, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='pictures/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='const',
            name='autumn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autumn', to='index_app.picture', verbose_name='Осень'),
        ),
        migrations.AddField(
            model_name='const',
            name='spring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spring', to='index_app.picture', verbose_name='Весна'),
        ),
        migrations.AddField(
            model_name='const',
            name='summer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='summer', to='index_app.picture', verbose_name='Лето'),
        ),
        migrations.AddField(
            model_name='const',
            name='winter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winter', to='index_app.picture', verbose_name='Зима'),
        ),
    ]
