# Generated by Django 4.1 on 2024-05-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_rate_name'),
    ]

    operations = [

        ]
