# Generated by Django 4.1 on 2024-05-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_rateitem_alter_city_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastmilerate',
            name='rate_item',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='city_from',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='city_to',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='LastMileRate',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='RateItem',
        ),
    ]
