# Generated by Django 4.1 on 2024-05-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0016_alter_order_date_from_alter_order_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='form_from',
            field=models.CharField(choices=[('FZ', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('OR', 'Юридическое лицо')], default='FZ', max_length=2, verbose_name='Форма собственности'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_payer',
            field=models.CharField(choices=[('FZ', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('OR', 'Юридическое лицо')], default='FZ', max_length=2, verbose_name='Форма собственности'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_to',
            field=models.CharField(choices=[('FZ', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('OR', 'Юридическое лицо')], default='FZ', max_length=2, verbose_name='Форма собственности'),
        ),
    ]
