# Generated by Django 4.1 on 2024-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0018_remove_cargo_seats_remove_itemorder_cardboard_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='prr_from',
            field=models.BooleanField(default=False, verbose_name='Погрузка при заборе груза (ПРР при заборе)'),
        ),
        migrations.AlterField(
            model_name='itemorder',
            name='prr_to',
            field=models.BooleanField(default=False, verbose_name='Выгрузка при доставке (ПРР при доставке)'),
        ),
    ]
