# Generated by Django 4.1 on 2024-07-04 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Электронная почта')),
                ('tel', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
