# Generated by Django 4.1 on 2024-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Электронная почта'),
        ),
    ]
