# Generated by Django 4.1 on 2024-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_app', '0002_alter_branch_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AddField(
            model_name='branch',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
